### ISSUE TITLE
The Agent should wait for the Server

### ISSUE THREAD

**Issue by dim4o** [MusalaSoft/atmosphere-docs#130]
- [x] If the Agent is started before the server - an error occurs.
- [x] Moreover the last info message is `Connection to server established.` but this is not true - the `Server` is not even started.

Error:
```
04 Oct 2017 11:45:43 - Could not establish connection to server on adress "127.0.0.1:8050". See log for information about the underlying exception.
javax.websocket.DeploymentException: Connection failed.
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientSocket._connect(GrizzlyClientSocket.java:427)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientSocket.access$000(GrizzlyClientSocket.java:103)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientSocket$1.call(GrizzlyClientSocket.java:234)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientSocket$1.call(GrizzlyClientSocket.java:230)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientSocket.connect(GrizzlyClientSocket.java:248)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientContainer.openClientSocket(GrizzlyClientContainer.java:95)
        at org.glassfish.tyrus.client.ClientManager$3$1.run(ClientManager.java:668)
        at org.glassfish.tyrus.client.ClientManager$3.run(ClientManager.java:717)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.glassfish.tyrus.client.ClientManager$SameThreadExecutorService.execute(ClientManager.java:871)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:516)
        at org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:322)
        at com.musala.atmosphere.agent.websocket.AgentDispatcher.connectToServer(AgentDispatcher.java:79)
        at com.musala.atmosphere.agent.AgentManager.connectToServer(AgentManager.java:197)
        at com.musala.atmosphere.agent.state.DisconnectedAgent.executeConnectCommand(DisconnectedAgent.java:72)
        at com.musala.atmosphere.agent.Agent.connectToServer(Agent.java:193)
        at com.musala.atmosphere.agent.Agent.main(Agent.java:248)
Caused by: java.net.ConnectException: Connection refused: no further information
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.glassfish.grizzly.nio.transport.TCPNIOConnectorHandler.onConnectedAsync(TCPNIOConnectorHandler.java:210)
        at org.glassfish.grizzly.nio.transport.TCPNIOConnectorHandler$1.connected(TCPNIOConnectorHandler.java:158)
        at org.glassfish.grizzly.nio.transport.TCPNIOConnection.onConnect(TCPNIOConnection.java:258)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:517)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.executeIoEvent(WorkerThreadIOStrategy.java:103)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.executeIoEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.nio.SelectorRunner.iterateKeyEvents(SelectorRunner.java:415)
        at org.glassfish.grizzly.nio.SelectorRunner.iterateKeys(SelectorRunner.java:384)
        at org.glassfish.grizzly.nio.SelectorRunner.doSelect(SelectorRunner.java:348)
        at org.glassfish.grizzly.nio.SelectorRunner.run(SelectorRunner.java:279)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
        at java.lang.Thread.run(Thread.java:748)
Connection to server established.
>>
```

**Comment by dim4o** [comment]
This is not a real defect. Simply use `exit` to exit from Server or Agent. If you exit with `Ctrl + C` or similar command the instance is still running. So the only correct way to exit from Server/Agent is to use `exit` command from it's CLI.

**Comment by dim4o** [comment]
A description of the `exit` command is added to the `Server` and `Agent` README.md
